# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.2
_src_path: https://github.com/jupyterlab/extension-template
author_email: wwill@cs.washington.edu
author_name: llm4eda
has_binder: true
has_settings: false
kind: server
labextension_name: llm4eda
project_short_description: A JupyterLab extension for using LLMs for EDA and data
    storytelling
python_name: llm4eda
repository: ''
test: true

